### ISSUE TITLE
Declarações BET, PV e GM (Issue #15 - Demandas) no SigRH

### ISSUE THREAD

**Issue by rafaelmassuncao** [EscolaDeSaudePublica/Demandas#18]
- [ ] Bolsa de Extensão Tecnológica
- [ ] Professor Visitante
- [ ] Gratificação de Magistério

**Comment by rafaelmassuncao** [comment]
Em andamento.

**Comment by uira** [comment]
Qual a diferença entre essa issue e a #15 ?

https://github.com/EscolaDeSaudePublica/Demandas/issues/15
