### ISSUE TITLE
Criação de Inscrição de Evento Cientifico - REDE BIBLIOSUS

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/Demandas#2]
Demanda do Cliente:
- Vamos realizar o IX ENCONTRO DA REDE BIBLIOSUS aqui em parceria com ESP CE, dias 04 e 05/12. Entregamos a solicitação para a certificação do evento para a Ana (Secretaria), ela vai enviar para você, mas ela falou que você é quem libera e prioriza o que precisa ser feito no sistema de gerenciamento de eventos científicos. Nossa urgência é que vamos receber trabalhos científicos e já está em cima. Contamos com você no sentido de liberar Rafael para fazer o que precisa.

- [x] Precisa de mais informações?

**Comment by NUCIT** [comment]
Segue anexo edital com cronograma.

**Comment by NUCIT** [comment]
Segue anexo edital com cronograma.

**Comment by NUCIT** [comment]
[Edital IX Encontro da Rede BiblioSUS(1).docx](https://github.com/EscolaDeSaudePublica/Demandas/files/3837459/Edital.IX.Encontro.da.Rede.BiblioSUS.1.docx)
[Edital IX Encontro da Rede BiblioSUS.pdf](https://github.com/EscolaDeSaudePublica/Demandas/files/3837460/Edital.IX.Encontro.da.Rede.BiblioSUS.pdf)
Segue edital em anexo.

**Comment by uira** [comment]
@NUCIT

**Comment by uira** [comment]
![image](https://user-images.githubusercontent.com/89998/68697624-fb092780-055d-11ea-9ceb-a852c0a34c8b.png)

**Comment by NUCIT** [comment]
Tudo certo! Obrigada!

**Comment by rafaelmassuncao** [comment]
Ok! Iniciando análise.

**Comment by rafaelmassuncao** [comment]
Precisamos de 2(dois) banners para o sistema e 01(uma) assinatura, que são enviados pela Ascom, nos formatos:

a) 365 x 290, PNG;
b) 560 x 400, PNG;
c) A assinatura digitalizada do Dr Marcelo, PNG.

Já enviei o e-mail solicitando.

**Comment by uira** [comment]
@rmadev-master Ariane, bom dia, vocês podem preparar isso? Precisam q cadastre no Sistema de Chamados?

**Comment by arianeadla** [comment]
Olá, eu preciso saber de onde veio essa demanda porque preciso de briefing!

**Comment by NUCIT** [comment]
O Encontro Estadual da Rede BiblioSUS é uma oportunidade para discussão e elaboração de estratégias de consolidação da Rede BiblioSUS Ceará, mediante articulações políticas e metodologias integradas que garantam a representatividade do conhecimento institucional em bases de dados bibliográficas especializadas, nos níveis estadual e municipal do Sistema Único de Saúde – SUS.
	A Secretaria da Saúde do Estado do Ceará (SESA), por intermédio do Núcleo de Ciência, Tecnologia e Inovação em Saúde (NUCIT), da Coordenadoria de Gestão do Trabalho e da Educação em Saúde (CGTES), incentiva a realização de pesquisas e produção de conhecimento em larga escala na rede SESA, com vistas ao cumprimento do preceito constitucional de saúde para todos com qualidade.

**Comment by arianeadla** [comment]
Olá, a arte do evento vai ser feita pela ASCOM daqui, correto? Ou já foi encaminhada para SESA?

**Comment by NUCIT** [comment]
Já foi solicitado aqui na SESA, porem não tivemos nenhuma resposta.

Segue anexo e-mail encaminhado a ASCOM da SESA.
![E-mail encaminhado à ASCOM](https://user-images.githubusercontent.com/57680646/68791541-4be55280-0628-11ea-8784-09fde520e038.png)

**Comment by arianeadla** [comment]
Mandei mensagem pra ASCOM  da SESA pra checar se a arte está sendo feita, pois não podemos pegar a demanda se eles já estiverem desenvolvendo essa arte!

**Comment by NUCIT** [comment]
BOM DIA!!!
Ariane, você teve resposta da ASCOM SESA?

Em qua., 13 de nov. de 2019 às 15:21, arianeadla <notifications@github.com>
escreveu:

**Comment by arianeadla** [comment]
Bom dia! Conversei com a Helga e ela disse que realmente quando o evento é da SESA, a arte é de responsabilidade deles. Sugiro contactá-los novamente, pois geralmente quando eles estão sobrecarregados, nos encaminham demandas, mas essa demanda não chegou aqui. Então é possível que a arte de vocês esteja na lista de afazeres deles! Qualquer dúvida, estou à disposição. O fixo lá é 3101.5220/ 5221

**Comment by arianeadla** [comment]
Bom dia, novidades no caso, rs! A Fatinha da ASCOM da SESA disse que a arte está em curso, mas não sabiam que iria ter inscrições online. Eles precisam de mais detalhes sobre isso para colocar nas artes e fazer o que é necessário! Mandem esse material no email deles, por favor!

**Comment by NUCIT** [comment]
Boa tarde, segue anexo arte confeccionada pela ASCOM/SESA.
![banner_IX_encontro_rede_bibliosus](https://user-images.githubusercontent.com/57680646/68882959-e5773780-06ee-11ea-84d8-0c1a031113ec.png)

**Comment by uira** [comment]
@NUCIT Victor Magalhães, vc consegue resolver essa aqui? 

Ou só o Rafel ?

**Comment by vicmagpac** [comment]
Somente Rafa!

**Comment by NUCIT** [comment]
@arianeadla 

Solicitamos divulgação do IX Encontro BiblioSUS no site da ESP CE. Entendemos ser de grande importância a divulgação do evento tanto no site da SESA como no site da ESP CE tendo em vista ser um evento realizado em parceria. Informamos que a mesma solicitação foi feita a ASCOM SESA.

SOBRE ENCONTRO BIBLIOSUS
O Encontro Estadual da Rede BiblioSUS é uma oportunidade para discussão e elaboração de estratégias de consolidação da Rede BiblioSUS Ceará, mediante articulações políticas e metodologias integradas que garantam a representatividade do conhecimento institucional em bases de dados bibliográficas especializadas, nos níveis estadual e municipal do Sistema Único de Saúde – SUS.

A Secretaria da Saúde do Estado do Ceará (SESA), por meio do Núcleo de Ciência, Tecnologia e Inovação em Saúde (NUCIT), incentiva a realização de pesquisas e produção de conhecimento em larga escala na rede SESA, com vistas ao cumprimento do preceito constitucional de saúde para todos com qualidade.

Assim sendo, realizará em parceria com a Escola de Saúde Pública Paulo Marcelo Martins Rodrigues (ESP), o IX Encontro da Rede BiblioSUS do Estado do Ceará, tema Rede BiblioSUS: Caminhos do Conhecimento para Inovação em Saúde, dias 04 e 05 de dezembro de 2019.

Link para inscrição: http://servicos.esp.ce.gov.br/eventos/2019/eve102019nucit/

Atenciosamente,
Maria do Carmo Aires Ribeiro

**Comment by NUCIT** [comment]
Boa tarde, @arianeadla 

Solicitamos que seja divulgada prorrogamento do prazo de submissão de trabalho do IX Encontro da Rede BiblioSUS.

Atual prazo: 15 de novembro de 2019 à 24 de novembro de 2019
Novo prazo: 15 de novembro de 2019 à 27 de novembro de 2019

Desde já agradeço e me disponibilizo para fornecer qualquer informação necessária.

**Comment by NUCIT** [comment]
Boa tarde!!! @arianeadla 

Solicitamos a confecção do certificado do IX Encontro da Rede BiblioSUS do Estado do Ceará - Rede BiblioSUS: Caminhos do Conhecimento para Inovação em Saúde. A imagem deverá ser enviada ao @rmadev-master / NUTIC em PNG, nas medidas 1170 x 826px,  já com as assinaturas da Dra. Alice Pequeno e Dr. Marcelo.

Desde já agradecemos e nos disponibilizamos para fornecer qualquer informação necessária.

Att,

Equipe NUCIT
Contatos:
Maria do Carmo - (85) 999879930 (Whatsapp)
Nicolas - (85) 996145177 (Whatsapp)
NUCIT - (85) 3101-5234

**Comment by uira** [comment]
Demanda implementada com sucesso!

(Faltou aqui o Feedback, os indicadores (numeros de inscritos/selecionados) e as ibagens - Foi pro [Banco de Idéias](https://github.com/EscolaDeSaudePublica/BancoDeIDeias/issues/11))
