### ISSUE TITLE
Edital 25/2019 - Aguardando edital

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/Demandas#5]
- [x] Adicionar registro do edital no SISWEB/SIGRH
- [x] Criar script da seleção
- [x] Criar aplicação
- [x] Testar aplicação
- [x] Publicar aplicação

**Comment by rafaelmassuncao** [comment]
Edital recebido. Iniciando trabalhos.

**Comment by rafaelmassuncao** [comment]
Concluído e publicado em: http://selecoes.esp.ce.gov.br/2019/edt252019ceres/
