### ISSUE TITLE
Edital 001/2020 - Medico da Família

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/Demandas#61]
- [x] Análise e correções na Minuta
- [x] Configuração do Sistema
- [x] Abertura das Inscrições
- [x] Atualizações até o resultado das inscrições.
- [x] Ajustes/Configuração da 1a Etapa
- [x] Ajustes no resultado final
- [x] Testes pré-publicação

**Comment by rafaelmassuncao** [comment]
Sistema ajustado/atualizado até o relatório preliminar das inscrições. Dados da aplicação no GitLab.

**Comment by rafaelmassuncao** [comment]
Edital publicado: 
:arrow_down: [edital.pdf](https://www.esp.ce.gov.br/wp-content/uploads/sites/78/2020/02/EDITAL-01-2020-DIPSA-Programa-M%C3%A9dico-da-Fam%C3%ADlia-APS.pdf)

Recebida a 1a Corrigenda do Certame (anexo). (04/02/2020 13h55 : Não publicado, sem previsão)
:arrow_down: [corrigenda1.pdf](https://github.com/EscolaDeSaudePublica/Demandas/files/4149787/1.CORRIGENDA_Edital.n.01_2020.pdf)

**Corrigenda publicada**: 
:arrow_down: [download.pdf](https://github.com/EscolaDeSaudePublica/Demandas/files/4192950/1.-CORRIGENDA_Edital-n.-01_2020.pdf)

**Comment by rafaelmassuncao** [comment]
Inscrições em andamento, através do link:
:link: http://selecoes.esp.ce.gov.br/2020/edt012020dipsa/

**Comment by rafaelmassuncao** [comment]
Versão atualizada e publicada: http://10.17.0.68/espce/p-sacs/commit/fa179d1e5d4b4955667829f1f1784e4c7ac07a28

**Comment by rafaelmassuncao** [comment]
Sistema pronto para testes finais: http://10.17.0.68/espce/p-sacs/commit/a9b52e8b7ea064cf57f7af64a7a05618c4399813

**Comment by rafaelmassuncao** [comment]
Concluído!
**Último commit**: http://10.17.0.68/espce/p-sacs/commits/edt012020dipsa
